image: python:3.8

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
# variables:
#   PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

# cache:
#   paths:
#     - .cache/pip
#     - venv/

before_script:
  - apt-get python
  - python --version  # Print out python version for debugging
  - python3 -m venv venv
  - source venv/bin/activate
  - pip install -r requirements.txt

stages:
  # - Static Analysis
  - Test

# flake8:
#   stage: Static Analysis
#   script:
#   - flake8 --max-line-length=150 --ignore=E266 scraper.py || true

pytest:
  stage: Test
  script:
  - python -m pytest || true

coverage:
  stage: Test
  allow_failure: true
  script:
  - python -m pytest --cov-report term-missing --cov=project || true