image: python:3.9

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - venv/

before_script:
  - python3 --version  # Print out python version for debugging
  - pip install -r requirements.txt


stages:
  - Static Analysis
  - Test
  - Job
  - Deploy

pytest:
  stage: Test
  script:
  - python3 -m pytest || true

pylint:
  stage: Static Analysis
  allow_failure: true
  script:
  - pylint scraper.py
  
scrape:
  stage: Job
  rules:
    - if: "$CI_PIPELINE_SOURCE == 'push'"
      when: manual
      allow_failure: true
    - if: "$CI_PIPELINE_SOURCE == 'schedule'"
      when: always
  script:
  - python3 scraper.py

deployment:
  stage: Deploy
  only:
    - main
  script:
    - git remote add heroku https://heroku:$HEROKU_API_KEY@git.heroku.com/scraper-proj.git
    - git push -f heroku master